### ISSUE TITLE
Create APK installer file for android :Đ

### ISSUE THREAD

**Issue by NLPV2011** [vtd182/locket_uploader#4]

**Comment by GBao6039** [comment]
👍

**Comment by vtd182** [comment]
Ver1: https://drive.google.com/file/d/10WXAvYnqmlRpZrGeHuO8zhbKZJ_aXRiq/view?usp=drive_link

**Comment by vtd182** [comment]
I am still developing a few more features so there is no release on github yet, the above is a test release with existing functions.
